# Generated by Django 5.2.4 on 2025-11-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chebitoch', '0002_tag_alter_comment_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
